networks:
  deploy-dev:
    driver: bridge
services:
  finance:
    container_name: finance
    image: finance
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8083
    ports:
      - "8083:8083"
    networks:
      - deploy-dev
    depends_on:
      - finance-db
  finance-db:
    container_name: finance-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
      PGPORT: 5436
    ports:
      - "5436:5436"
    networks:
      - deploy-dev
    volumes:
      - .postgres-data:/data
volumes:
  postgres-data: